name: Auto Remove BaseURL

on:
  push:
    branches: [ main ] # 监听 main 分支的推送

jobs:
  remove-baseurl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 确保获取所有分支

      - name: Remove baseURL from nuxt.config.ts
        run: |
          # 使用 sed 命令移除 app.baseURL 配置
          sed -i -e "/baseURL: '\/nuxt-read\/',/d" nuxt.config.ts

      - name: Check if target branch exists
        id: check_branch
        run: |
          if git show-ref --quiet refs/heads/no-base-url-branch; then
            echo "Branch exists"
          else
            echo "Branch does not exist"
            git checkout -b no-base-url-branch # 创建新分支
          fi

      - name: Checkout the target branch
        run: |
          git checkout no-base-url-branch

      - name: Add and commit the changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add nuxt.config.ts
          git commit -m "Automatically remove baseURL from nuxt.config.ts"
          git push origin no-base-url-branch