name: Auto Sync and Remove BaseURL

on:
  push:
    branches: [ main ]

jobs:
  sync-and-remove-baseurl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}  # 使用个人访问令牌

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync main branch to no-base-url-branch
        run: |
          # 检查远程分支是否存在
          if git ls-remote --heads origin no-base-url-branch | grep -q 'no-base-url-branch'; then
            git checkout no-base-url-branch
            git pull origin main
          else
            git checkout -b no-base-url-branch
          fi

      - name: Modify nuxt.config.ts
        run: |
          # 使用更可靠的方式修改配置文件
          sed -i '/baseURL:/c\    // baseURL: removed for this branch,' nuxt.config.ts

      - name: Commit and push changes
        run: |
          git add nuxt.config.ts
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: sync from main and remove baseURL"
            git push origin no-base-url-branch
          fi